### PR TITLE
Integrate Mayhem

### PR DESCRIPTION
**Pull request by rnshah9**

### CODE REVIEW

**Comment by xansec** [comment]
Cmake changes looks ok to me.

**Comment by xansec** [comment]
Whoop, spoke too soon. Could you please resolve 
1. Multi-stage build
2. Correct usage of filepath
3. Generic project name

**Comment by xansec** [comment]
I went ahead and resolved this.

**Comment by rnshah9** [comment]
Sorry, I must have missed this!

**Comment by rnshah9** [comment]
Wait, I did resolve this in [my fork](https://github.com/rnshah9/mayhem-minlzma/commit/2e6c1835520413295dd5558c770d880ee4145677). Was there something else I had to do to make the commit show up in this PR?

**Comment by xansec** [comment]
Yeah, since the PR is closed no new changes would have shown up. You would have had to create a new PR. No worries, since in any case it's resolved now.

**Pull request merged**
